apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  metadata:
  - name: redisHost
    value: YOUR_REDIS_HOST_HERE
  - name: redisPassword
    value: YOUR_REDIS_PASSWORD_HERE

# apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
# kind: SecretProviderClass
# metadata:
#   name: secret-provider-kv     # This ID, is what you use in your Volume Mapping to reference this.
# spec:
#   provider: azure
#   parameters:
#     usePodIdentity: "true"
#     keyvaultName: "tfkv17580"
#     objects:  |
#       array:
#         - |
#           objectName: arc-hostname       
#           objectType: secret
#         - |
#           objectName: arc-key       
#           objectType: secret        
#     tenantId: "72f988bf-86f1-41af-91ab-2d7cd011db47"                    # the tenant ID of the KeyVault  

# ---
# apiVersion: dapr.io/v1alpha1
# kind: Component
# metadata:
#   name: statestore
# spec:
#   type: state.redis
#     volumeMounts:
#     - name: secrets-store-inline
#       mountPath: "/mnt/secrets-store"
#       readOnly: true
#   volumes:
#     - name: secrets-store-inline
#       csi:
#         driver: secrets-store.csi.k8s.io
#         readOnly: true
#         volumeAttributes:
#           secretProviderClass: "secret-provider-kv"
#   # metadata:
#   # - name: redisHost
#   #   value: YOUR_REDIS_HOST_HERE
#   # - name: redisPassword
#   #   value: YOUR_REDIS_PASSWORD_HERE