name: dapr-distributed-calculator
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build docker image
        run: | 
          REGISTRY=${{ env.ACRSERVER }} make build
      - name: Publish docker image
        # if: github.event_name != 'pull_request'
        run: |
          docker login -u ${{ secrets.ACRID }} -p ${{ secrets.ACRSECRET }} ${{ env.ACRSERVER }}
          REGISTRY=${{ env.ACRSERVER }} make push
    env:
      ACRSERVER: ${{ secrets.ACRSERVER }}
